SELECT SUM(TOTAL_CHAMADAS) as TOTAL_CHAMADAS, SUM(ABANDONO) as ABANDONO, SUM(ATENDIDO) as ATENDIDO, CAST((SUM(ABANDONO)* 100)/SUM(TOTAL_CHAMADAS) AS NUMERIC(10,2))||'%' as PERC_ABD,
CAST((SUM(ATENDIDO)* 100)/SUM(TOTAL_CHAMADAS) AS NUMERIC(10,2))||'%' as PERC_ATD
    FROM VW_CALLCENTER_CONSOLIDADO WHERE DT_CALL_SYSTEM_DATA = '18-07-2019' --AND CC_QUEUE = 'NOME_DA_FILA' AND HORARIOS > '00:00:00' AND HORARIOS < '23:59:00'
GO
